config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'splash#index'

  resources :groups, only: [:index, :show, :new, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Payment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :payments

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    total = 0
    payments.each do |payment|
      total += payment.amount
    end
    total
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :payments

  validates :name, presence: true
  validates :email, presence: true
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show]

  def index
    @groups = Group.all.order(created_at: :desc)
  end

  def show
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        flash[:success] = 'Post saved successfully'
        format.html { redirect_to '/groups' }
      else
        flash.now[:error] = 'Error: Post could not be saved'
        format.html { render :new }
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :group_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show]

  def index
    @payments = Payment.all
  end

  def show; end

  def new
    @payment = Group.find_by_id(params[:group_id]).payments.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    @payment.group_id = Group.find_by_id(params[:group_id]).id

    respond_to do |format|
      if @payment.save
        flash[:success] = 'Post saved successfully'
        format.html { redirect_to group_path(@payment.group_id) }
      else
        flash.now[:error] = 'Error: Post could not be saved'
        format.html { render :new }
      end
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div id='categories'>
  <div class='nav_categories'>
	  <i class="fa fa-bars fa-2x"></i>
    <h1>Categories</h1>
    <i class="fa fa-search fa-2x"></i>
  </div>

  <% @groups.each do |group| %>
    <%= link_to group, :action => 'go', class: 'category_link' do %>
      <div class='category'>
        <p class='icon'><%= group.icon %></p>
        <div class='name_date'>
          <p><%= group.name %></p>
          <p><%= group.created_at.strftime('%d-%b-%Y') %></p>
        </div>
        <p class='total_amount'><strong>$<%= group.total_amount %></strong></p>
      </div>
    <% end %>
  <% end %>

  <div class='new_category_border'>
    <%= link_to 'ADD NEW CATEGORY', '/groups/new', class: 'new_category' %>
  </div>
</div>

app/views/groups/new.html.erb
<div id='groups_new'>
  <h1 class='hello_error'><%= flash[:error] %></h1>

  <%= form_with model: @group, class: 'form' do |f| %>
  <div class='groups_form'>
    <%= link_to groups_url, class: 'signup_back' do %>
      <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
    <%= f.submit class: 'submit' %>
  </div>
  <div class='category_inputs'>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.text_field :icon, placeholder: 'Icon' %>
  </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div id='payments'>
  <div class='back_title'>
    <%= link_to '/groups', class: 'payment_back' do %>
      <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
    <h1>Payments</h1>
  </div>

  <div class='payments_section'>
    <p class='total_payment'>Total Payment: <%= @group.total_amount %></p>

    <% @payments.each do |payment| %>
        <div class='payment'>
        <div class='name_date_payments'>
          <p><%= payment.name %></p>
          <p><%= payment.created_at.strftime('%d-%b-%Y') %></p>
        </div>
          <p>$<strong><%= payment.amount %></strong></p>
        </div>
    <% end %>
  </div>

  <div class='new_payment'>
    <%= link_to 'ADD NEW PAYMENT', new_group_payment_path(group_id: @group), class: 'add_new_payment' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='notice_alert'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class='link_to_sign'>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.name %></strong>.
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<div id='payment_form'>
  <h1 class='hello_error'><%= flash[:error] %></h1>

  <%= form_with model: @payment, url: group_payments_path, class: 'form' do |f| %>
    <div class='payments_form'>
      <%= link_to groups_url, class: 'signup_back' do %>
        <i class="fa fa-arrow-left fa-2x"></i>
      <% end %>
      <%= f.submit class: 'submit' %>
    </div>
    <div class='name_amount'>
      <%= f.text_field :name, placeholder: 'Name' %>
      <%= f.number_field :amount, step: 0.01, placeholder: 'Amount' %>
    </div>
  <% end %>
</div>

app/views/splash/index.html.erb
<div id='splash_screen'>
  <h1>Mèxico Transfer</h1>

  <%= link_to 'Log In', new_user_session_path, class: 'login'%>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'signup' %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>users#show</h1>